import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./main.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200&display=swap"
          rel="stylesheet"
      />
      <body suppressHydrationWarning={true} className={inter.className}>{children}</body>
      </html>
  );
}
